o := test.restore_of("func");
r := o(2, 4);
if (r != 11)
    fail("restored function gave incorrect result: " + string(r));
